### ISSUE TITLE
insmod wimboot gives 'grub_sprintf' error

### ISSUE THREAD

**Issue by steve6375** [aIive/builds#1]
I have MBR working the iPXE initrd /wimboot method using a Win10 ISO file and I want to get UEFI64 boot working also.

I copied wimboot.mod (from https://github.com/aIive/builds/tree/master/x86_64-efi) to my  grub2 folder /boot/grub/x86_64-efi, UEFI64 booted to a version of Ubuntu grub2, but `insmod wimboot` returns a 

> symbol 'grub_sprintf' not found

 error.
Do I have to use a special version of grub.efi? If so where can I obtain it?

Also, if I am mounting a Win10 ISO as (loop) and then booting from it, what\where is the boot bootmgfw.efi file? Do I need to specify it? If so, is it the normal EFI file which is found inside the boot.wim which is inside the ISO?

**Comment by a1ive** [comment]
You should use grub-mkimage.exe to build grub.efi.
`grub-mkimage -O x86_64-efi -p /boot/grub -o grubx64.efi normal part_gpt part_msdos fat exfat ntfs chain  configfile loopback probe progress regexp test help search wimboot gzio cpio newc`
Or you can download grub2-filemanager (https://github.com/a1ive/grub2-filemanager)

**Comment by a1ive** [comment]
> Also, if I am mounting a Win10 ISO as (loop) and then booting from it, what\where is the boot bootmgfw.efi file? Do I need to specify it? If so, is it the normal EFI file which is found inside the boot.wim which is inside the ISO?

(loop)/efi/boot/bootx64.efi
I recommand use win7x64 bootmgfw.efi.
more info:
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=414244 (Chinese)
https://www.tnctr.com/topic/351320-multiboot-toolkit-v230multiboot-system-uefilegacy/page/48/ (Turkish)

**Comment by steve6375** [comment]
Thanks for reply. It would be extremely useful if the wimboot.mod module could be loaded using insmod from a standard grub2 version? Is this possible?

**Comment by a1ive** [comment]
It's possible. But there are other modules that need to call 'grub_sprintf' function.

**Comment by steve6375** [comment]
I just want to make wimboot work for most uefi grub2 standard versions, I don't care about other modules?

**Comment by a1ive** [comment]
You could download offical grub source code and move 'grub_sprintf' from [grub-core/kern/misc.c](https://github.com/a1ive/grub/blob/373825d9635ea687e59c59289b176c2335a6b961/grub-core/kern/misc.c#L1204) to grub-core/commands/efi/wimboot.c then compile.
