### ISSUE TITLE
Filename length issue with UEFI wimboot

### ISSUE THREAD

**Issue by steve6375** [aIive/builds#4]
when inserting a file using wimboot:

@:$**filename**.tag:xx.txt

if $filename = WIN10Test2.iso then it fails - the filename seems to be Win10Test2.iso.tagregfr ??
if $filename = WIN10Test.iso then it works OK (filename is Win10test.iso.tag)

I think this was also an issue in iPXE wimboot which was fixed a while ago.

![image](https://user-images.githubusercontent.com/1469350/60381012-1871a500-9a46-11e9-85b9-10432ff33ffd.png)

**Comment by a1ive** [comment]
![Snipaste_2019-06-30_15-10-32](https://user-images.githubusercontent.com/10670106/60393686-c155f800-9b4b-11e9-917b-f6582ca31ba7.png)
seems to work.

**Comment by steve6375** [comment]
The filename is wrong - check the file exists in X:\WINDOWS\SYSTEM32 folder - you should see that it is not called WIN10TEST2.iso.tag.

**Comment by a1ive** [comment]
The offical version has the same problem.
![Snipaste_2019-06-30_16-51-17](https://user-images.githubusercontent.com/10670106/60394469-5d393100-9b57-11e9-9cb4-46b67f49fc44.png)

**Comment by steve6375** [comment]
No - 
[wimboot.zip](https://github.com/aIive/builds/files/3342699/wimboot.zip)
wimboot 2017-05-17 has a limit of 31 characters
![wimbootfilenametest](https://user-images.githubusercontent.com/1469350/60394572-5510cf80-9b1e-11e9-9e9d-8c115cdcda1f.jpg)

**Comment by a1ive** [comment]
![1](https://user-images.githubusercontent.com/10670106/60394817-78f30600-9b5c-11e9-9979-a1e5f315ddf8.png)
![2](https://user-images.githubusercontent.com/10670106/60394818-7f817d80-9b5c-11e9-86a8-5348ca6a0049.png)

Name: wimboot517
Size: 51392 bytes (50 KiB)
CRC32: 5A6AFD68

**Comment by steve6375** [comment]
hmmm... that's strange. So why does it work for me?
```
		echo Using ${pp}/sources/boot.wim...
		set installiso=${ip}/WINDOWS/${isoname}
		save_env -f /wimboot/null.cfg installiso
		linux16 /wimboot/wimboot
		initrd16 \
#		newc:bootmgr:(loop)${pp}/bootmgr \
        newc:winpeshl.ini:/wimboot/winpeshl.ini \
		newc:null.cfg:/wimboot/null.cfg \
        newc:startup.bat:/wimboot/startup.bat \
		newc:$isoname.tag:(loop)${pp}/boot/bcd \
		newc:boot.wim:(loop)${pp}/sources/boot.wim \
		newc:bcd:(loop)${pp}/boot/bcd \
		newc:boot.sdi:(loop)${pp}/boot/boot.sdi
		drivemap -s hd0 hd1
		boot
```

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/60400763-71d5f300-9b70-11e9-8cb7-6f28651c1fb9.png)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/60400795-ced1a900-9b70-11e9-9965-0dd22b098910.png)
Same menu with long file name (error because file should end in .tag).

**Comment by a1ive** [comment]
Please have a try.
[wimboot.zip](https://github.com/aIive/builds/files/3343807/wimboot.zip)
![1](https://user-images.githubusercontent.com/10670106/60408404-5bbc4700-9bf1-11e9-83bd-a19d95dc2815.png)
![2](https://user-images.githubusercontent.com/10670106/60408410-5e1ea100-9bf1-11e9-999f-d402933bbca9.png)

**Comment by steve6375** [comment]
Thanks, is this 32 it or 64 bit?

**Comment by a1ive** [comment]
64bit

**Comment by steve6375** [comment]
looks good 👍

**Comment by steve6375** [comment]
What is length limit now? Seems to be more than 32 characters.
P.S. Can filenames with spaces in name be used/specified  (not needed - just interested to know if they are possible).

**Comment by a1ive** [comment]
> P.S. Can filenames with spaces in name be used/specified (not needed - just interested to know if they are possible).
> [Edit] I will answer my own Q - yes - use @:"xxxx yyyy": for filename.
> So usage should be:
> wimboot [--gui] [--rawbcd] [--rawwim] [--pause] [--index=n] @:"anyname":"/path/to/afile" @:"boot.wim":"/path/to/test.wim" @:"bootmgfw.efi":"/path/to/test.efi" @:"bcd":"/path/to/bcd" @:"boot.sdi":"/path/to/boot.sdi"

You could also use backslash.

**Comment by a1ive** [comment]
> What is length limit now? Seems to be more than 32 characters.
defined in vdisk.h
https://github.com/a1ive/wimboot/blob/259555fdc4ca35b11b3cd2b9c9a36bcdb1b2e97e/src/vdisk.h#L579
